import { type LotteryConfig, type LotteryType, type GeneratorStrategy } from "@/types/lottery"

export const LOTERIAS: Record<LotteryType, LotteryConfig> = {
  megasena: {
    id: "megasena",
    nome: "Mega-Sena",
    nomeExibicao: "Mega-Sena",
    cor: "#209869",
    corSecundaria: "#6edba6",
    poolSize: 60,
    pickCount: 6,
    maxPick: 20,
    ranges: [[1, 10], [11, 20], [21, 30], [31, 40], [41, 50], [51, 60]],
    icon: "🍀",
    precoAposta: 5.00,
  },
  lotofacil: {
    id: "lotofacil",
    nome: "Lotofácil",
    nomeExibicao: "Lotofácil",
    cor: "#930089",
    corSecundaria: "#cc5ec4",
    poolSize: 25,
    pickCount: 15,
    maxPick: 20,
    ranges: [[1, 5], [6, 10], [11, 15], [16, 20], [21, 25]],
    icon: "🎯",
    precoAposta: 3.00,
  },
  quina: {
    id: "quina",
    nome: "Quina",
    nomeExibicao: "Quina",
    cor: "#260085",
    corSecundaria: "#7b61ff",
    poolSize: 80,
    pickCount: 5,
    maxPick: 15,
    ranges: [[1, 16], [17, 32], [33, 48], [49, 64], [65, 80]],
    icon: "⭐",
    precoAposta: 2.50,
  },
  lotomania: {
    id: "lotomania",
    nome: "Lotomania",
    nomeExibicao: "Lotomania",
    cor: "#f78100",
    corSecundaria: "#ffb347",
    poolSize: 100,
    pickCount: 50,
    ranges: [[0, 19], [20, 39], [40, 59], [60, 79], [80, 99]],
    icon: "🔥",
    precoAposta: 3.00,
  },
  maismilionaria: {
    id: "maismilionaria",
    nome: "+Milionária",
    nomeExibicao: "+Milionária",
    cor: "#002d6b",
    corSecundaria: "#4d8fd6",
    poolSize: 50,
    pickCount: 6,
    maxPick: 12,
    ranges: [[1, 10], [11, 20], [21, 30], [31, 40], [41, 50]],
    icon: "💎",
    precoAposta: 6.00,
  },
  duplasena: {
    id: "duplasena",
    nome: "Dupla Sena",
    nomeExibicao: "Dupla Sena",
    cor: "#a61324",
    corSecundaria: "#e85d6f",
    poolSize: 50,
    pickCount: 6,
    maxPick: 15,
    ranges: [[1, 10], [11, 20], [21, 30], [31, 40], [41, 50]],
    icon: "🎲",
    precoAposta: 2.50,
  },
  timemania: {
    id: "timemania",
    nome: "Timemania",
    nomeExibicao: "Timemania",
    cor: "#00ff48",
    corSecundaria: "#66ff8c",
    poolSize: 80,
    pickCount: 10,
    ranges: [[1, 16], [17, 32], [33, 48], [49, 64], [65, 80]],
    icon: "⚽",
    precoAposta: 3.50,
  },
  diadesorte: {
    id: "diadesorte",
    nome: "Dia de Sorte",
    nomeExibicao: "Dia de Sorte",
    cor: "#cb7917",
    corSecundaria: "#e8a94d",
    poolSize: 31,
    pickCount: 7,
    maxPick: 15,
    ranges: [[1, 7], [8, 14], [15, 21], [22, 31]],
    icon: "☀️",
    precoAposta: 2.50,
  },
  supersete: {
    id: "supersete",
    nome: "Super Sete",
    nomeExibicao: "Super Sete",
    cor: "#a8cf45",
    corSecundaria: "#c9e87a",
    poolSize: 10,
    pickCount: 7,
    ranges: [[0, 9]],
    icon: "7️⃣",
    precoAposta: 2.50,
  },
}

export const LOTERIAS_LISTA = Object.values(LOTERIAS)

export const ESTRATEGIAS: GeneratorStrategy[] = [
  {
    id: "aleatorio",
    nome: "Aleatório Puro",
    descricao: "Números totalmente aleatórios, sem critério estatístico",
    icon: "🎰",
  },
  {
    id: "frequencia",
    nome: "Mais Frequentes",
    descricao: "Prioriza números que mais apareceram no histórico",
    icon: "📊",
  },
  {
    id: "frequencia_recente",
    nome: "Frequência Recente",
    descricao: "Foca nos números quentes dos últimos 30 concursos",
    icon: "🔥",
  },
  {
    id: "atrasados",
    nome: "Números Atrasados",
    descricao: "Prioriza números que estão há mais tempo sem sair",
    icon: "⏰",
  },
  {
    id: "balanceado",
    nome: "Balanceado",
    descricao: "Equilibra pares/ímpares e distribui por faixas",
    icon: "⚖️",
  },
  {
    id: "hibrido",
    nome: "Híbrido Inteligente",
    descricao: "Combina frequência, atraso e equilíbrio estrutural",
    icon: "🧠",
  },
  {
    id: "lotocore",
    nome: "LotoCore AI",
    descricao: "Motor avançado: genético + Markov + Monte Carlo + Bayesiano",
    icon: "🚀",
  },
]

export const NAV_ITEMS = [
  { href: "/dashboard", label: "Dashboard", icon: "BarChart3" },
  { href: "/gerador", label: "Gerador", icon: "Sparkles" },
  { href: "/concursos", label: "Concursos", icon: "Search" },
  { href: "/heatmap", label: "Mapa de Calor", icon: "Flame" },
  { href: "/raio-x", label: "Raio-X", icon: "ScanLine" },
]

export const NAV_ITEMS_AUTH = [
  { href: "/meus-jogos", label: "Meus Jogos", icon: "Star" },
  { href: "/conferencia", label: "Conferência", icon: "CheckCircle" },
  { href: "/assistente", label: "Assistente IA", icon: "Bot" },
]
